# Generated by Django 4.0.4 on 2022-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edituserprofile', '0002_alter_editprofile_country_alter_editprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='profile_image',
            field=models.CharField(max_length=500),
        ),
    ]
