# Generated by Django 4.0.4 on 2022-05-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edituserprofile', '0002_alter_editprofile_country_alter_editprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
