# Generated by Django 4.0.4 on 2022-05-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edituserprofile', '0003_alter_editprofile_profile_image'),
        ('edituserprofile', '0003_delete_editprofile'),
    ]

    operations = [
    ]
