# Generated by Django 4.0.4 on 2022-05-11 11:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellitem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='userid',
        ),
        migrations.AddField(
            model_name='listitem',
            name='itemurl',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='poster',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='base_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='other_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='images'), size=4),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
