# Generated by Django 4.0.4 on 2022-05-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='base_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image2',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image3',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image4',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image5',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='itemname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='main_image',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
