# Generated by Django 4.0.4 on 2022-05-13 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellitem', '0002_listitem_base_price_listitem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listitem',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='base_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='condition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='itemname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='main_image',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
