# Generated by Django 4.0.4 on 2022-05-11 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0002_remove_listitem_userid_listitem_itemurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='other_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='images/'), size=4),
        ),
    ]
