# Generated by Django 4.0.4 on 2022-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0002_remove_listitem_userid_listitem_itemurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='other_images',
        ),
        migrations.AddField(
            model_name='listitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
    ]
