# Generated by Django 4.0.4 on 2022-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0003_listitem_highest_bid_listitem_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='highest_bid',
        ),
    ]
