# Generated by Django 4.0.4 on 2022-05-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0003_remove_listitem_other_images_listitem_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='poster',
        ),
    ]
