# Generated by Django 4.0.4 on 2022-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0004_remove_listitem_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
