# Generated by Django 4.0.4 on 2022-05-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0003_alter_listitem_main_image_and_more'),
        ('sellitem', '0004_remove_listitem_poster'),
    ]

    operations = [
    ]
