# Generated by Django 4.0.4 on 2022-05-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0005_listitem_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='highest_bid',
        ),
    ]
