# Generated by Django 4.0.4 on 2022-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0007_alter_listitem_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='image2',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='image3',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='image4',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='image5',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='main_image',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
