# Generated by Django 4.0.4 on 2022-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0008_alter_listitem_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='highest_bidder',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
