# Generated by Django 4.0.4 on 2022-05-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0008_alter_listitem_image2_alter_listitem_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='itemurl',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='poster',
        ),
    ]
