# Generated by Django 4.0.4 on 2022-05-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0008_remove_listitem_itemurl_remove_listitem_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='main_image',
            field=models.CharField(max_length=9999),
        ),
    ]
