# Generated by Django 4.0.4 on 2022-05-06 11:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=0, max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='frontpage.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=9999)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.people')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_rank', models.CharField(blank=True, max_length=255)),
                ('starting_price', models.FloatField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('first_image', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='frontpage.itemimage')),
            ],
        ),
    ]
