# Generated by Django 4.0.4 on 2022-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='', max_length=9999),
        ),
    ]
