# Generated by Django 4.0.4 on 2022-05-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_bio_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
