# Generated by Django 4.0.4 on 2022-05-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sellitem', '0008_alter_listitem_image2_alter_listitem_image3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_cvc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='purchase',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellitem.listitem'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='street_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
