# Generated by Django 4.0.4 on 2022-05-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_purchase_card_cvc_purchase_card_expiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item_id',
            new_name='item',
        ),
    ]
