# Generated by Django 4.0.4 on 2022-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_purchase_card_cvc_purchase_card_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
