# Generated by Django 4.0.4 on 2022-05-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_purchase_rating'),
        ('checkout', '0003_rename_item_id_purchase_item'),
    ]

    operations = [
    ]
