# Generated by Django 4.0.4 on 2022-05-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_merge_20220512_2219'),
        ('checkout', '0004_merge_20220513_1000'),
    ]

    operations = [
    ]
